---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
'Twas brillig, and the slithy toves
Did gyre and gimble in the wabe;
All mimsy were the borogoves,
And the mome raths outgrabe.

"Beware the Jabberwock, my son!
The jaws that bite, the claws that catch!
Beware the Jubjub bird, and shun
The frumious Bandersnatch!"

## Second Verse
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;

Then took the other, as just as fair,
And having perhaps the better claim,
Because it was grassy and wanted wear;
Though as for that the passing there
Had worn them really about the same,

## Third Verse
The sun was shining on the sea,
Shining with all his might:
He did his very best to make
The billows smooth and bright--
And this was odd, because it was
The middle of the night.

The moon was shining sulkily,
Because she thought the sun
Had got no business to be there
After the day was done--
"It's very rude of him," she said,
"To come and spoil the fun!"

## Last Verse
Don't feel small. We all have
been demoted. Go on being

moon or rock or orb, bouyant
and distant, smallest craft ball

at Vanevenhoven's Hardware
spray-painted purple or day-glow

orange for a child's elliptical vision
of fish line, cardboard and foam.

No spacecraft has touched you,
no flesh met the luster of your

heavenly body. Little cold one, blow
your horn. No matter what you are

planet, and something other than
planet, ancient but not "classical,"

the controversy over what to call you
light-hours from your ears. On Earth

we tend to nurture the diminutive,
root for the diminished. None 

of your neighbors knows your name.
Nothing has changed. If Charon's

not your moon, who cares? She
remains unmoved, your companion.
